/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_CPUTemperatureMeter
#define HEADER_CPUTemperatureMeter
/*
htop
(C) 2004-2006 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "Meter.h"

#include <time.h>

#include "debug.h"

extern int CPUTemperatureMeter_attributes[];

extern MeterType CPUTemperatureMeter;

#endif
